" Highlight search
set hlsearch
" Set incremental search
set incsearch
" Yank(Copy) directly to system clipboard
set clipboard=unnamedplus

set tabstop=4
set noexpandtab
set autoindent

" Use ctrl + [hjkl] for navigation in insert mode
inoremap <C-k> <C-o>gk
inoremap <C-h> <Left>
inoremap <C-l> <Right>
inoremap <C-j> <C-o>gj

" Use a line cursor within insert mode and a block cursor everywhere else.
" Reference chart of values:
"   Ps = 0  -> blinking block.
"   Ps = 1  -> blinking block (default).
"   Ps = 2  -> steady block.
"   Ps = 3  -> blinking underline.
"   Ps = 4  -> steady underline.
"   Ps = 5  -> blinking bar (xterm).
"   Ps = 6  -> steady bar (xterm).
let &t_SI = "\e[6 q"    "Insert mode
let &t_EI = "\e[2 q"	"All other modes

" Set timeout to avoid lag between changing modes
set ttimeout
set ttimeoutlen=1
set ttyfast

" Show line numbers (also relative from current line)
set number relativenumber
" Basic Commands

" Navigate around window
nnoremap <C-l> <C-w><C-l>
nnoremap <C-h> <C-w><C-h>
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>

" Replace all the searched word in the same file
nnoremap <Leader>r :%s///g<Left><Left>
nnoremap <Leader>rc :%s///gc<Left><Left><Left>
